// <auto-generated />
using System;
using EllaX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EllaX.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("EllaX.Core.Entities.Peer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTimeOffset>("FirstSeenDate");

                    b.Property<DateTimeOffset>("LastSeenDate");

                    b.Property<decimal?>("Latitude");

                    b.Property<string>("LocalAddress");

                    b.Property<decimal?>("Longitude");

                    b.Property<string>("Name");

                    b.Property<string>("RemoteAddress");

                    b.HasKey("Id");

                    b.ToTable("Peers");
                });
#pragma warning restore 612, 618
        }
    }
}
